fix syntax error due to usage of let
webpack-licenses-plugin.js:18
  let license
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode